name: Deploy to server

on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16.15.0'
                  cache: 'yarn'

            - run: yarn install --immutable

            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                  host: ${{secrets.DEPLOYMENT_HOST}}
                  username: ubuntu
                  key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
                  script: |
                      cd ~/ufc-api-reader
                      git pull
                      ./scripts/run.sh

        env:
            CI: true
