name: Deploy to server

on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16.15.0'
                  cache: 'yarn'

            - run: yarn install --immutable

            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              env:
                  DEPLOYMENT_HOST: ${{secrets.DEPLOYMENT_HOST}}
                  DB_URL: ${{secrets.DB_URL}}
              with:
                  host: ssh.justinelmore.dev
                  username: ubuntu
                  key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
                  run: |
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      cd ~/ufc-api-reader
                      git pull
                      echo "DB_URL=$DB_URL" >> .env
                      yarn
                      chmod -x ./scripts/run.sh
                      ./scripts/run.sh

        env:
            CI: true
